[workspace]
members = ["core", "desktop", "web"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
gpui = { path = "../../crates/gpui", package = "gpui-ce" }
gpui_platform = { path = "../../crates/gpui_platform", package = "gpui_ce_platform" }
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
